export type CaseItem = {
  slug: string;
  title: string;
  context: string;
  clientType?: "corporate" | "startup" | "sme" | "individual" | "agency";
  projectType?: "web-app" | "mobile-app" | "fullstack" | "ai-system" | "enterprise" | "product";
  problem?: string;
  intervention?: string;
  highlights?: string[];
  outcome?: string[];
  next?: string;
  stack?: string[];
  timeline?: string;
  featured?: boolean;
};

export const cases: CaseItem[] = [
  {
    slug: "lifelearn-holdings",
    title: "LifeLearn Holdings — Singapore SaaS Platform",
    context: "Web application consultant for veterinary practice management software serving clinics across Asia-Pacific.",
    clientType: "startup",
    projectType: "web-app",
    problem: "Outdated backend causing frequent data issues and 40+ hours/month of manual engineering fixes. Frontend needed to work around legacy constraints while maintaining user experience quality.",
    intervention: "Designed front-end solutions and data handling workflows that worked around backend limitations. Built robust error handling, optimized data flows, and implemented UX improvements that reduced user friction.",
    highlights: [
      "Built resilient frontend layer on legacy backend",
      "Implemented smart caching and data sync strategies",
      "Developed reusable component library",
      "Remote collaboration across Singapore and Finland",
    ],
    outcome: [
      "Saved 40+ engineering hours/month on manual fixes",
      "Improved system reliability without backend rewrite",
      "3+ years of ongoing partnership",
      'CEO: "Our most valuable person regarding technology"',
    ],
    next: "Continue supporting platform evolution and new feature development",
    stack: ["React", "TypeScript", "REST APIs", "PostgreSQL"],
    timeline: "2017-2020 (Ongoing)",
    featured: true,
  },
  {
    slug: "rga-global-brands",
    title: "R/GA — Global Brand Digital Experiences",
    context: "Senior Software Engineer & Tech Lead at R/GA Jakarta, delivering world-class digital experiences for Fortune 500 clients.",
    clientType: "agency",
    projectType: "web-app",
    problem: "Deliver high-fidelity, performant web experiences for global brands with tight deadlines, cross-timezone collaboration, and exacting quality standards.",
    intervention: "Led front-end development for multiple high-profile campaigns. Collaborated with designers, strategists, and engineers across Jakarta, New York, and London. Established coding standards and mentored junior developers.",
    highlights: [
      "Google — Interactive campaign experiences",
      "MOCA Museum — Digital exhibition platform",
      "Reejig — AI-powered workforce platform",
      "Westholme — Premium brand digital presence",
    ],
    outcome: [
      "Delivered 10+ major brand campaigns on time",
      "Inducted into R/GA Hall of Immortality (March 2022)",
      "Mentored 5+ junior engineers on best practices",
      "Established component library used across projects",
    ],
    next: "Completed engagement; moved to strategic leadership roles",
    stack: ["React", "Next.js", "GSAP", "Three.js", "Node.js"],
    timeline: "2021-2022",
    featured: true,
  },
  {
    slug: "syntax-solution",
    title: "Syntax Solution — Tech Consultancy Co-founder",
    context: "Co-founded tech consultancy serving Indonesian enterprises and startups, serving as VP of Engineering/Product and CPTO.",
    clientType: "startup",
    projectType: "enterprise",
    problem: "Built company from scratch requiring strategic planning, team building, product development, client acquisition, and delivery—simultaneously. Needed to establish service framework while delivering for paying clients.",
    intervention: "Established service framework and delivery processes. Recruited cross-functional teams. Architected multiple client solutions including fleet management, mobile finance, access control, and robotics platforms.",
    highlights: [
      "Fleet Management System (MTF)",
      "Mobile Finance Application",
      "Access Control & Robotics Platform",
      "Enterprise SaaS Development",
    ],
    outcome: [
      "Grew from 0 to 8+ active projects",
      "Delivered 12+ production systems",
      "Built team of 10+ engineers and designers",
      "Established recurring client relationships",
    ],
    next: "Continue growing consultancy and productized offerings",
    stack: ["React", "Next.js", "Node.js", "Flutter", "PostgreSQL", "AWS"],
    timeline: "2017-Present",
    featured: true,
  },
  {
    slug: "mandiri-tunas-finance",
    title: "MTF — Fleet Management System",
    context: "Enterprise fleet management solution for Mandiri Tunas Finance, one of Indonesia's largest multi-finance companies.",
    clientType: "corporate",
    projectType: "enterprise",
    problem: "Manual fleet tracking and document management causing operational delays. No centralized view of vehicle status, maintenance schedules, or documentation across the organization.",
    intervention: "Designed and built comprehensive fleet management system. Implemented real-time tracking, document digitization, maintenance scheduling, and reporting dashboards for management visibility.",
    highlights: [
      "Real-time fleet tracking and status",
      "Document digitization and management",
      "Automated maintenance scheduling",
      "Executive reporting dashboards",
    ],
    outcome: [
      "Centralized view of entire fleet operations",
      "Reduced document processing time by 60%",
      "Improved maintenance compliance",
      "Delivered within enterprise security requirements",
    ],
    next: "Phase 2 expansion to additional business units",
    stack: ["React", "Node.js", "PostgreSQL", "AWS", "Docker"],
    timeline: "2023-Present",
    featured: true,
  },
  {
    slug: "karyakilat",
    title: "KaryaKilat — Productized Microsite Service",
    context: "Founder & architect of productized service enabling Indonesian professionals to launch premium microsites in 24 hours.",
    clientType: "sme",
    projectType: "product",
    problem: "Insurance agents, property agents, freelancers, and SMEs need professional online presence to build credibility and capture leads, but lack technical skills or budget for custom development.",
    intervention: "Built template-based platform enabling non-technical users to launch professional microsites quickly. Includes hosting, SSL, mobile optimization, lead capture, and SEO best practices out of the box.",
    highlights: [
      "24-hour delivery guarantee",
      "Mobile-first, SEO-optimized templates",
      "Built-in lead capture and WhatsApp integration",
      "Hosting and SSL included",
    ],
    outcome: [
      "20+ clients launched in first 3 months",
      "Average setup time: 24 hours vs weeks traditional",
      "Recurring revenue product business",
      "Expanding to additional professional verticals",
    ],
    next: "Scale to 100+ clients and launch premium tiers",
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "Vercel"],
    timeline: "2024-Present",
    featured: true,
  },
  {
    slug: "komunal",
    title: "Komunal — GovTech Platform",
    context: "Tech Manager leading engineering team to build government technology solutions for smart city initiatives.",
    clientType: "startup",
    projectType: "fullstack",
    problem: "Small team needed to deliver complex full-stack solutions while building engineering capabilities and maintaining code quality standards.",
    intervention: "Led team of 4-5 developers, established code quality standards, implemented CI/CD pipelines, and provided hands-on technical leadership. Made architectural decisions aligned with business goals while mentoring team on full-stack development.",
    highlights: [
      "Team leadership and mentorship",
      "CI/CD pipeline implementation",
      "Agile methodology adoption",
      "Cross-functional collaboration",
    ],
    outcome: [
      "Built proficient full-stack development team",
      "Established clean code standards",
      "Delivered critical project milestones on time",
      "Strong technical foundation for future growth",
    ],
    next: "Completed contract engagement",
    stack: ["React", "Node.js", "PostgreSQL", "Docker", "CI/CD"],
    timeline: "Sep 2023 - Feb 2024",
    featured: false,
  },
  {
    slug: "yoona",
    title: "Yoona — Beauty E-Commerce Platform",
    context: "Engineering Manager and Lead Engineer building early-stage beauty e-commerce platform from ground up.",
    clientType: "startup",
    projectType: "fullstack",
    problem: "Early-stage startup needed to build entire technology infrastructure, develop custom e-commerce solutions, and establish engineering team while managing limited resources.",
    intervention: "Acted as technology consultant directly to CTO. Led technical decision-making, architecture design, and hands-on development for MVP and complex features. Managed hiring, budgeting, vendor integrations, and stakeholder communications.",
    highlights: [
      "Full-stack MVP development",
      "Custom e-commerce solutions",
      "Technology consultant to CTO",
      "Team building and hiring",
      "3rd party vendor integrations",
    ],
    outcome: [
      "Delivered complete technology foundation",
      "Established engineering team and processes",
      "Launched platform successfully",
      "Implemented security and compliance standards",
    ],
    next: "Completed contract as company scaled",
    stack: ["React", "Node.js", "PostgreSQL", "AWS", "Payment Gateways"],
    timeline: "Jan 2022 - Aug 2023",
    featured: false,
  },
  {
    slug: "cakra-studio",
    title: "CakraStudio — Digital Agency",
    context: "Senior Web Developer and Analyst leading web development team for client projects and agency growth.",
    clientType: "agency",
    projectType: "web-app",
    problem: "Agency needed standardized processes, technical estimation capabilities, and strong team leadership to deliver consistent client results.",
    intervention: "Led web development team, managed client discussions, created technical estimations, and established standardized processes including WordPress template boilerplates and web service standards.",
    highlights: [
      "Team leadership and management",
      "Client relationship management",
      "Standardized development processes",
      "WordPress template system",
    ],
    outcome: [
      "Improved project delivery consistency",
      "Established technical estimation framework",
      "Built reusable template systems",
      "Enhanced agency visibility and reputation",
    ],
    next: "Moved to co-found CIAYO",
    stack: ["WordPress", "PHP", "JavaScript", "MySQL"],
    timeline: "Jul 2012 - Jun 2015",
    featured: false,
  },
  {
    slug: "ciayo-corp",
    title: "CIAYO Corp — Webtoon & Digital Media Platform",
    context: "Co-founder & Lead Frontend Developer building Indonesia's leading webtoon and digital entertainment platform.",
    clientType: "startup",
    projectType: "fullstack",
    problem: "Building digital media platform from scratch in emerging market. Needed to scale from concept to millions of users while pivoting business model multiple times.",
    intervention: "Led frontend development from founding through multiple pivots. Built and scaled web applications serving millions of monthly users. Established engineering culture and processes as team grew.",
    highlights: [
      "Webtoon reader platform",
      "Community and social features",
      "Content management system",
      "Mobile-responsive design",
    ],
    outcome: [
      "Scaled to millions of monthly active users",
      "Grew company from startup to 51-200 employees",
      "Successfully pivoted product lines multiple times",
      "5+ years building core platform",
    ],
    next: "Completed engagement; company continues growing",
    stack: ["React", "Node.js", "MongoDB", "AWS"],
    timeline: "2015-2020",
    featured: false,
  },
];